#!/bin/bash
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

REF_DIR=$(dirname "$(realpath "$0")")
RTL_FOLDER=$(realpath "$REF_DIR/../../rtl")

cd ${REF_DIR}

# cleanup
rm -rf obj_dir
rm -f ref.vcd

../assemble.sh ref.s

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --trace \
    -cc ${RTL_FOLDER}/top.sv \
    --exe ref_tb.cpp \
    -y ${RTL_FOLDER} \
    --prefix "Vtop" \
    -o Vtop \
    --LDFLAGS "-lgtest -lgtest_main -lpthread"

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file
obj_dir/Vtop
